require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'App' do
  use_react_native!(:path => '../node_modules/react-native')
end
