import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { mergeConfig, yamlList } from './lib/codeql-config.mjs';

const DEFAULTS = readFileSync(fileURLToPath(new URL('./codeql-config.yml', import.meta.url)), 'utf8');

test('yamlList reads only its own block, strips comments and one pair of quotes', () => {
  const text = 'queries:\n  - uses: a # c\n  -\n  - "q"\n  - \'s\'\nother:\n  - x\n';
  assert.deepEqual(yamlList(text, 'queries'), ['uses: a', 'q', 's']);
  assert.deepEqual(yamlList(text, 'missing'), []);
});

test('the package defaults carry the suite, the suppression pack and the directories nobody scans', () => {
  assert.deepEqual(yamlList(DEFAULTS, 'queries'), ['uses: security-and-quality']);
  assert.deepEqual(yamlList(DEFAULTS, 'packs'), ['codeql/javascript-queries:AlertSuppression.ql']);
  for (const dir of ['.workflows', '.claude/worktrees', 'ios', 'android']) assert.ok(yamlList(DEFAULTS, 'paths-ignore').includes(dir), dir);
});

test('no file of its own: the defaults, as a generated file', () => {
  const merged = mergeConfig(DEFAULTS, null);
  assert.match(merged, /^# Generated by resolve-code-scanning-config: the family's defaults with /);
  assert.match(merged, /\nname: code-scanning\n/);
  assert.deepEqual(yamlList(merged, 'queries'), yamlList(DEFAULTS, 'queries'));
  assert.deepEqual(yamlList(merged, 'packs'), yamlList(DEFAULTS, 'packs'));
  assert.deepEqual(yamlList(merged, 'paths-ignore'), yamlList(DEFAULTS, 'paths-ignore'));
});

test('paths-ignore adds to the defaults, in order, without repeating one', () => {
  const merged = mergeConfig(DEFAULTS, 'paths-ignore:\n  - src/graphql/generated # codegen\n  - ios\n  - "src/*/messages.ts"\n');
  const ignored = yamlList(merged, 'paths-ignore');
  assert.deepEqual(ignored.slice(-2), ['src/graphql/generated', 'src/*/messages.ts']);
  assert.equal(ignored.filter((entry) => entry === 'ios').length, 1);
});

test('name, queries and packs replace the defaults when the file sets them', () => {
  const merged = mergeConfig(DEFAULTS, 'name: my-app # shown in the UI\nqueries:\n  - uses: security-extended\npacks:\n  - acme/queries\n');
  assert.match(merged, /\nname: my-app\n/);
  assert.deepEqual(yamlList(merged, 'queries'), ['uses: security-extended']);
  assert.deepEqual(yamlList(merged, 'packs'), ['acme/queries']);
});

test('an empty name falls back to the default one', () => {
  assert.match(mergeConfig(DEFAULTS, 'name:\n'), /\nname: code-scanning\n/);
});

test('a key the merge does not carry is an error naming it and the file', () => {
  assert.throws(() => mergeConfig(DEFAULTS, 'paths:\n  - src\ndisable-default-queries: true\npaths:\n  - lib\n', 'c.yml'), /^Error: c\.yml sets paths, disable-default-queries, which the merge with the family's defaults does not carry; only name, queries, packs, paths-ignore are merged$/m);
});
