#!/usr/bin/env bash
# Render every reusable workflow's `on.workflow_call` interface - its inputs
# (type, required), secrets (required) and outputs - as
# packages/dev-config/interfaces.json.
#
# check-consumer-contract compares each caller's `with:`, `secrets:` and the
# outputs it reads against this file. It ships in the package rather than being
# read from the workflows, because the checker runs before Setup on nothing but
# node, and a consumer that installs the package has the package, not the
# workflows. test/render-interfaces.bats fails when the committed file and this
# output disagree, so an input added here without a re-render is caught here,
# not in a consumer's run.
#
# self-* workflows are left out: they are this repository's own CI, never
# called by a consumer.
#
# Usage: render-interfaces.sh [OUT]   (default: packages/dev-config/interfaces.json)
set -euo pipefail
source "$(dirname "$0")/../lib/common.sh"
require_cmd yq

root="$(cd "$(dirname "$0")/../.." && pwd)"
out="${1:-$root/packages/dev-config/interfaces.json}"

files=()
for file in "$root"/.github/workflows/*.yml; do
  case "$(basename "$file")" in self-*) continue ;; esac
  [ "$(yq -r '.on | has("workflow_call")' "$file")" = "true" ] || continue
  files+=("$file")
done
[ "${#files[@]}" -gt 0 ] || die "no reusable workflow found under $root/.github/workflows"

# One object per file, keyed by its name, merged in file order and then sorted,
# so the output only changes when an interface does. `$item` is yq's variable,
# not the shell's.
# shellcheck disable=SC2016
yq ea -o=json -I=2 '
  {
    (filename | sub(".*/", "")): (.on.workflow_call | {
      "inputs": ((.inputs // {}) | map_values({"type": (.type // "string"), "required": (.required // false)})),
      "secrets": ((.secrets // {}) | map_values({"required": (.required // false)})),
      "outputs": ((.outputs // {}) | keys)
    })
  } as $item ireduce ({}; . * $item)
  | {"$comment": "Generated by scripts/self/render-interfaces.sh from .github/workflows - do not edit. check-consumer-contract holds every call a consumer makes to these interfaces.", "workflows": (. | sort_keys(.))}
' "${files[@]}" > "$out"
log "wrote the interfaces of ${#files[@]} workflows to $out"
