// The CodeQL configuration a repository is scanned with: this package's
// defaults (codeql-config.yml beside package.json) with the repository's own
// .github/codeql/codeql-config.yml merged over them. check-code-scanning.yml
// resolves it before the analysis and `check-code-scanning` before a local one,
// through resolve-code-scanning-config, so the two read the same text.
//
// Only the four keys the family uses are merged. Any other top-level key in the
// repository's file would be dropped without a word, which is how a local
// "clean" stops meaning a CI "clean", so it is an error naming the key.

/**
 * The items of the top-level YAML list `key` in `text`, with trailing comments,
 * blanks and one pair of surrounding quotes stripped. Scoped to that key's block on purpose: an unscoped
 * search for `- codeql/...` would also match such a line in a comment, in
 * another key's list, or in prose.
 */
export function yamlList(text, key) {
  const lines = text.split('\n');
  const start = lines.findIndex((line) => line.startsWith(`${key}:`));
  if (start === -1) return [];
  const items = [];
  for (const line of lines.slice(start + 1)) {
    if (/^[^ #-]/.test(line)) break;
    const item = /^\s*-\s*(.*)$/.exec(line);
    if (!item) continue;
    const value = item[1]
      .replace(/\s*#.*$/, '')
      .trimEnd()
      .replace(/^(["'])(.*)\1$/, '$2');
    if (value !== '') items.push(value);
  }
  return items;
}

const KEYS = ['name', 'queries', 'packs', 'paths-ignore'];

/** Whether the top-level key `key` is present in `text`. */
const hasKey = (text, key) => text.split('\n').some((line) => line.startsWith(`${key}:`));

/** The scalar value of the top-level `name:` in `text`, or null. */
const nameOf = (text) => {
  const match = /^name:[ \t]*(.*?)[ \t]*(?:#.*)?$/m.exec(text);
  return match && match[1] !== '' ? match[1] : null;
};

/**
 * The defaults with `appText` merged over them, as YAML text. `appText` null is
 * a repository with no file of its own: the defaults alone. `source` names the
 * repository's file in an error.
 */
export function mergeConfig(defaultsText, appText, source = '.github/codeql/codeql-config.yml') {
  const app = appText ?? '';
  const unknown = app
    .split('\n')
    .map((line) => /^([A-Za-z][\w-]*):/.exec(line)?.[1])
    .filter((key) => key !== undefined && !KEYS.includes(key));
  if (unknown.length > 0) {
    throw new Error(
      `${source} sets ${[...new Set(unknown)].join(', ')}, which the merge with the family's defaults does not carry; only ${KEYS.join(', ')} are merged`,
    );
  }
  const pick = (key) => (hasKey(app, key) ? yamlList(app, key) : yamlList(defaultsText, key));
  const ignored = [...new Set([...yamlList(defaultsText, 'paths-ignore'), ...yamlList(app, 'paths-ignore')])];
  return [
    `# Generated by resolve-code-scanning-config: the family's defaults with ${source} merged over them.`,
    `name: ${nameOf(app) ?? nameOf(defaultsText)}`,
    'queries:',
    ...pick('queries').map((entry) => `  - ${entry}`),
    'packs:',
    ...pick('packs').map((entry) => `  - ${JSON.stringify(entry)}`),
    'paths-ignore:',
    ...ignored.map((entry) => `  - ${JSON.stringify(entry)}`),
    '',
  ].join('\n');
}
