#!/usr/bin/env node
// Which native stack a consumer is: an Expo app, whose ios/ and android/ are
// generated by a prebuild and never committed, or a bare React Native app,
// whose ios/ and android/ are committed source.
//
//   node lib/native-stack.mjs [--root DIR] [--input expo|bare|'']
//
// prints `expo` or `bare` on stdout, and why on stderr. The native build
// workflows resolve their own native-stack input by the same rule, in the same
// order:
//
//   1. the native-stack input, when the caller sets one;
//   2. expo, when package.json lists expo in dependencies or devDependencies
//      and git tracks nothing under ios/ (it is absent, or gitignored);
//   3. bare otherwise.
//
// The contract checker, check.yml's Expo health gate and the bundle and mobile
// security scanners all ask this module, so a repository is one stack to all
// of them. It needs node and git and nothing else: the contract checker runs
// it before the setup action has installed anything.
import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { isProgram } from './is-program.mjs';

export const STACKS = ['expo', 'bare'];

/**
 * The stack, as `{ stack, reason }`, from what the rule reads: the input, the
 * consumer's dependencies (both tables merged), and whether git tracks ios/.
 * An input that is neither stack nor empty is an error, not a guess.
 */
export function resolveNativeStack({ input = '', dependencies = {}, iosTracked = false } = {}) {
  const value = input.trim();
  if (value !== '') {
    if (!STACKS.includes(value)) {
      throw new Error(`::error::native-stack is "${value}": expected expo, bare or empty (empty detects it from the repository)`);
    }
    return { stack: value, reason: 'the native-stack input' };
  }
  if (!dependencies.expo) return { stack: 'bare', reason: 'expo is not a dependency in package.json' };
  if (iosTracked) return { stack: 'bare', reason: 'git tracks ios/, so the native projects are committed source' };
  return { stack: 'expo', reason: 'expo is a dependency and git tracks no ios/' };
}

/**
 * Whether git tracks anything under `dir` in the repository at `root`. Outside
 * a git repository, or without git at all, nothing is tracked.
 */
export function isTracked(root, dir, run = spawnSync) {
  const result = run('git', ['-C', root, 'ls-files', '--', dir], { encoding: 'utf8' });
  return result.status === 0 && result.stdout.trim() !== '';
}

/**
 * package.json's dependencies and devDependencies, merged. No package.json is
 * no dependencies; one that does not parse is an error naming the file.
 */
export function readDependencies(root, read = readText) {
  const file = path.join(root, 'package.json');
  const text = read(file);
  if (text === null) return {};
  let pkg;
  try {
    pkg = JSON.parse(text);
  } catch (error) {
    throw new Error(`::error::${file} is not valid JSON: ${error.message}`);
  }
  return { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
}

/** A file's text, or null when it cannot be read. */
export function readText(file) {
  try {
    return readFileSync(file, 'utf8');
  } catch {
    return null;
  }
}

/** The stack of the repository at `root`, as `{ stack, reason }`. */
export function nativeStack(root, input = '', { read = readText, tracked = isTracked } = {}) {
  return resolveNativeStack({
    input,
    dependencies: readDependencies(root, read),
    // Asked only when it can matter, so a repository without expo never needs git.
    iosTracked: input.trim() === '' && tracked(root, 'ios'),
  });
}

export function parseArgs(argv, cwd = process.cwd()) {
  const options = { root: cwd, input: '' };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const value = argv[i + 1];
    if (arg !== '--root' && arg !== '--input') throw new Error(`::error::unknown argument: ${arg} (usage: native-stack.mjs [--root DIR] [--input expo|bare])`);
    if (value === undefined) throw new Error(`::error::${arg} needs a value`);
    options[arg.slice(2)] = value;
    i++;
  }
  return options;
}

/** Command-line entry; returns the exit code. */
export function main(
  argv = process.argv.slice(2),
  { stdout = process.stdout, stderr = process.stderr, cwd = process.cwd(), read = readText, tracked = isTracked } = {},
) {
  try {
    const { root, input } = parseArgs(argv, cwd);
    const { stack, reason } = nativeStack(path.resolve(root), input, { read, tracked });
    stdout.write(`${stack}\n`);
    stderr.write(`native stack: ${stack} (${reason})\n`);
    return 0;
  } catch (error) {
    stderr.write(`${error.message}\n`);
    return 1;
  }
}

if (isProgram(import.meta.url, process.argv[1])) process.exitCode = main();
